### ISSUE TITLE
pretrained models 

### ISSUE THREAD

**Issue by JoshonSmith** [flyywh/Recurrent-Multi-Frame-Deraining#2]
**excuse me . where can I get the pretrained_models

thanks !**

**Comment by flyywh** [comment]
Thanks for your attention! The pretrained models will be released in the future. I will notify you once they are released.

**Comment by mengxiangyudlut** [comment]
thanks！

**Comment by JoshonSmith** [comment]
thanks ! 
I also want to know when you release this paper.

**Comment by JoshonSmith** [comment]
has this paper been released？

**Comment by flyywh** [comment]
The paper is available here: https://ieeexplore.ieee.org/abstract/document/9439949
